### ISSUE TITLE
support leptos 0.5.x betas

### ISSUE THREAD

**Issue by beckend** [Baptistemontan/leptos_i18n#15]
This change just happened: https://github.com/leptos-rs/leptos/pull/918

**Comment by Baptistemontan** [comment]
If you want to switch to leptos 0.5.0-beta you can use this branch: https://github.com/Baptistemontan/leptos_i18n/tree/leptos_0.5_beta

I will close this issue with a PR merging this branch to main when leptos stabilize 0.5.x

**Comment by Baptistemontan** [comment]
I've created a branch with leptos v0.5.0-beta2 and with the changes comming in v0.2.

Those changes being:
- The removal of `i18n.json`, the configuration is now in the cargo manifest.
- Plurals are now declared in a sequence instead of a map in the json file.

Any feedback on those changes would be appreciated!
