### ISSUE TITLE
Yaml support

### ISSUE THREAD

**Issue by francisbr** [Baptistemontan/leptos_i18n#59]
Hi,

Just leaving this here, I know it is most likely a big endeavour. But would you be open to support yaml file for the translations? I am not asking to replace json, as some people might prefer that, but maybe a way to support both a bit like rust-i18n does?

It's far from important or anything, json works just fine, just a personal preference on my end. :)

**Comment by Baptistemontan** [comment]
I would be open to accept yaml file format (I would be open for any format to be honest), I don't think deserialization does'nt do anything JSON specific, the only thing holding this back is my lack of knowledge with this format, I can't provide exemples on how to write those (I could learn thought).

I guess supporting this format would'nt be a lot of work, probably gated behind a feature to not compile the whole `serde_json`   if YAML is what's being parse (yaml is already a dependencie for parsing the manifest).

I'll look into it

**Comment by Baptistemontan** [comment]
Made a woupsi, it's TOML that is used for the manifest

**Comment by Baptistemontan** [comment]
Well it seams yaml is supported out of the box, I can write strings, plurals and subkeys without problems.
I pushed a branch with the support, it would really help if you could test it! https://github.com/Baptistemontan/leptos_i18n/tree/yaml_support

**Comment by francisbr** [comment]
I have a pretty small codebase, but the switch was seemless. I am using simple interpolation, plurals (with range) & subkeys and nothing wrong there.

Warning, I don't have: namespaces, component interpolation. So yeah not 100% full coverage, but since the features didn't change, only the file type?

**Comment by francisbr** [comment]
I do am getting this warning though
![image](https://github.com/Baptistemontan/leptos_i18n/assets/16530390/63d8781f-5d51-49c5-bf58-a7372febbae1)

**Comment by Baptistemontan** [comment]
Glad to hear! Namespaces should'nt be a problem, they don't affect parsing

For the warning it's because you use a git url and it pulls the whole workspace, with the tests and exemples... Won't appear once publish.

I'll merge this, add some tests for it and will probably publish the first release candidat, I'm happy where v0.2 is right now

**Comment by francisbr** [comment]
Oh actually small thing, I don't know how picky you want to be. I tried renaming my files to en.yml instead of the *.yaml. technically for YAML both .yml & .yaml are supported.

Personally I'm fine with yaml but if you want to handle both.

**Comment by Baptistemontan** [comment]
Humm that's a good point, it's far easier to just stick to one file extension so if there is an error you can just bubble it instead of trying another extension and losing the first error which would possibly be the relevant one. Not sure what to do.
Support for another extension won't be breaking changes tho, so could be added later without problem, could you open a new issue about that?  I will think about it after the release candidat

**Comment by francisbr** [comment]
Will do! Thank you!

**Comment by francisbr** [comment]
Follow up ticket created here
https://github.com/Baptistemontan/leptos_i18n/issues/63

**Comment by Baptistemontan** [comment]
I'm translating the tests for json to yaml, and I kind of like the syntax haha, might give it a try another day

**Comment by Baptistemontan** [comment]
json to yaml website still my bestfriend tho
